-- Triangle WMS Pro - Corrections colonnes inscription SaaS
-- À exécuter sans supprimer les données.

ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS price_monthly NUMERIC(12,2) DEFAULT 0;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS max_users INTEGER DEFAULT 0;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS max_warehouses INTEGER DEFAULT 0;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS max_products INTEGER DEFAULT 0;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS max_movements_monthly INTEGER DEFAULT 0;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS trial_days INTEGER DEFAULT 15;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS modules TEXT DEFAULT '';
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS can_use_reports BOOLEAN DEFAULT true;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS can_use_qr BOOLEAN DEFAULT true;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS can_use_advanced_inventory BOOLEAN DEFAULT true;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS can_use_documents BOOLEAN DEFAULT true;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS can_use_chat BOOLEAN DEFAULT true;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS can_use_ai BOOLEAN DEFAULT true;

ALTER TABLE companies ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS business_type VARCHAR(150) DEFAULT '';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS responsible_name VARCHAR(255) DEFAULT '';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS email VARCHAR(255) DEFAULT '';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS phone VARCHAR(100) DEFAULT '';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS address TEXT DEFAULT '';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS plan_id INTEGER;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(50) DEFAULT 'trial';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMP;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users ADD COLUMN IF NOT EXISTS fullname VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS password VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(80) DEFAULT 'magasinier';
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_id INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_super_admin BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS badge_code VARCHAR(150);
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS company_id INTEGER;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS plan_id INTEGER;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS start_date DATE DEFAULT CURRENT_DATE;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'trial';
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'free_trial';
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS payment_mode VARCHAR(50) DEFAULT 'manual';
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS is_payment_required BOOLEAN DEFAULT false;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_companies_email ON companies(email);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_subscriptions_company_id ON subscriptions(company_id);
